name: Emotional Smoke Jumper
favicon: null
layout_spectrum: 0.7935804177541286
typography_spectrum: 0.16264441306702793
title: Emotional Smoke Jumper
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-51531154-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.20471928268671036
  lightness: 0.7461661042179912
  saturation: 0.5434585500042886
  rhythmicContrast: 0.7983712300192565
purpose: []
