name: Emotional Smoke Jumper
favicon: null
layout_spectrum: 0
typography_spectrum: 0.61805
title: Emotional Smoke Jumper
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eadac1'
    - '#1b1c17'
    - '#97907e'
    - '#d47a57'
    - '#eeb182'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
